# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Photo Grid"
  description: Display information from a collection in a photo grid
  icon: apps
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: photo-grid-1
  hide_collection_pages: true
  collection: contact-index
  exclude_pages: []
  limit: 2
  button_text: View Profile

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_text:
    comment: If this is left blank, no button will be shown