# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Breadcrumbs"
  description: The page breadcrumbs, determined from the page url
  icon: keyboard_double_arrow_right
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  include_breadcrumbs:
  link_text: Front Page
  link_url: /home
  link_classes:
  rel_permalink:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  link_url:
    comment: The url for the first link within the breadcrumb
  link_text:
    comment: The text for the first link within the breadcrumb
  
