# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile Content"
  description: Display the content from another page
  icon: font_download
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  collection:
  page:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: