# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile Details"
  description: Display details such as major/role for student/faculty profiles
  icon: account_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name:
  major:
  major_url:
  graduation_year:
  role:
  organization:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
