# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Contact Info"
  description: Display contact details for a person
  icon: contact_mail
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  contact_details:
    phone: (304) 293-1234
    fax:
    email: firstname.lastname@mail.wvu.edu
    office: 408 Arnold Hall
    office_url: "#"
    website: "#"
    cv_download_url: "#"
  border: false
  top_margin: mt-3

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  website:
    type: url