# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Calendar Events"
  description: Display events with details such as their time and location
  icon: calendar_today
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: calendar-events-1
  heading: Calendar Events Headline
  subheading: Subhead goes here.
  postscript: Put additional info or <a href="#">links</a> here.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  postscript:
    type: html
    options:
      link: true