# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Filter"
  description: Radio box inputs for filtering content
  icon: filter_alt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name:
  inputs:
  include_filter:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    comment: The name to identify this filter
  inputs:
    comment: An array of strings that are the labels of all inputs 
  include_filter:
    comment: Should this filter be displayed
