# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile Hero"
  description: A simple jumbotron-style component for calling extra attention to possible actions.
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: 
  collection: 
  page: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: