module:
  imports:
    - path: components.local
    - path: github.com/cloudcannon/bookshop/hugo/v3
    # - path: "github.com/Enterprise-Success/WVU-POC-common"
  replacements: 
    - components.local -> ../component-library
    # Uncomment the following line for development with a local theme.
    # - 'github.com/Enterprise-Success/WVU-POC-common -> ../../WVU-POC-common/'