# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Action Hero"
  description: A simple jumbotron-style component for calling extra attention to possible actions.
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: action-hero-1
  heading:
    text: "ACTION HERO HEADLINE"
    hierarchy: h1
  body_text: This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
  button: bookshop:generic/button!
  secondary_link:
    pre_text: Here is a
    link_text: Secondary Call to Action
    link_url: "#"
  background_image: https://static.wvu.edu/global/images/patterns/wvu/background__topo-white--2.0.0.svg
  full_width_or_backpage: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  hierarchy:
    type: select
    options:
      values:
        - h1
        - h2
  body_text:
    type: textarea
  full_width_or_backpage:
    comment: If false, the content takes up the full width available. If true, the content takes up a subset of the width available.