# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Colored Boxes"
  description: Link to pages with information displayed in coloured boxes.
  icon: collections_bookmark
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: colored-boxes-1
  heading:
  subheading:
  items:
    - heading: Item heading
      text: Item description
      url: /item-url
  color: multicolor
  postscript: Put additional info or <a href="#">links</a> here.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  postscript:
    type: html
    options:
      link: true
  text:
    type: textarea
  color:
    type: select
    options:
      values:
        - multicolor
        - blue