# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Table Of Contents"
  description: A group of links to function as a table of contents for the section
  icon: toc
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  use_nav:
  links:
    - url:
      text:
  current_url:
  title:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  links: 
    hidden: use_nav
  title:
    comment: The title of the current page