# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Page Collection"
  description: Display pages based on the chosen collection
  icon: collections_bookmark
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: page-collection-1
  heading: Page collection headline
  subheading: Subhead goes here.
  hide_collection_pages: true
  collection: content
  exclude_pages: []
  limit: 4
  display_image: false
  button_text: Read More
  postscript: Put additional info or <a href="#">links</a> here.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  display_image:
    comment: If the collection page has a thumbnail url and this is selected, it will be displayed
  button_text:
    comment: If this is left blank, no button will be shown
  postscript:
    type: html
    options:
      link: true
