# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Text Input"
  description: A simple text input for use within a form
  icon: create
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id:
  label:
  placeholder:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  id: exampleFormControlInput1
  label: Name
  placeholder: Your Name

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
