# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Article Hero"
  description: A hero component intended to be used at the top of article pages. 
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: article-hero-1
  display_hero: true
  hero_text_alignment: left
  heading: "Magazine Article"
  subheading: Subhead goes here.
  hide_author: false 
  author: Adam Glenn
  published_at: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  published_at: "2022-05-28T00:30:00.00Z"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  published_at:
    type: datetime
  hide_author: 
    type: checkbox
  hero_text_alignment:
    comment: Select the alignment for the content
    type: choice
    options:
      allow_empty: false
      values:
        - name: Left
          id: left
          icon: align_horizontal_left
        - name: Center
          id: center
          icon: format_align_center
        - name: Right
          id: right
          icon: align_horizontal_right