# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Hero"
  description: A hero component intended to be used at the top of pages when just a heading is needed. 
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: article-hero-1
  heading: "Heading"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
