# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Collection Labels Warning"
  description: A warning to be displayed within collection components while editing
  icon: warning_amber
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: "collection label"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
