# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile Info"
  description: Display details about a person
  icon: account_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  major:
  graduation_year:
  role:
  organization:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
