# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Quicklinks"
  description: A block of links
  icon: link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name:
  heading_text: Quicklinks
  links:
    - text: "Link Text"
      url: "#"
  postscript: View <a href="#">All quicklinks</a>.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  postscript:
    type: html
    options:
      link: true
      bold: true
      italic: true