# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Textarea Input"
  description: A textarea input for use within a form
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id:
  label:
  rows:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  id: exampleFormControlTextarea1
  label: Message
  rows: 3

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  rows:
    type: number
    min: 1
    max: 10
    step: 1
