# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Contact Form"
  description: Contact details plus a form
  icon: account_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  header: Header Text
  location:
    heading: At the office
    address: >-
      <p><strong>West Virginia University</strong></p><p>1345 Market St, Suite
      900</p><p>Morgantown, WV 26505</p>
  phone:
    heading: By Phone
    location: West Virginia University
    phone: (304) 293-1234
  fax:
    heading:
    number:
  email:
    heading: By Email
    location: West Virginia University
    email: email@mail.wvu.edu
  other:
    heading: Contact an Individual
    subheading: Looking for someone specific?
    link:
      url: '#'
      text: Meet the Team
  form: bookshop:simple/form

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  header: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: