# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description: A generic link component styled as a button - to be used inside other components
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Button text
  style: primary
  size: lg
  link: "#"
  link_target: "#"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  style:
    type: select
    options:
      values:
        - primary
        - wvu-gold
  size:
    type: select
    options:
      values:
        - name: Large
          id: lg
        - name: Small
          id: sm
  link_target:
    hidden: true
